#!/usr/bin/env bash
# Infra Jejak — one-time project setup.
#
# This repo ships only the Flutter/Dart source (lib/), assets, and
# pubspec.yaml — not the android/ and ios/ platform folders. Those are
# normally machine-generated by the Flutter CLI to match YOUR installed
# Flutter SDK version, which is safer than shipping pre-built platform
# files that might not match your setup.
#
# Run this ONCE after unzipping, before opening the project in Android
# Studio:
#
#   chmod +x setup.sh && ./setup.sh
#
# It is safe to run even if android/ios already exist — `flutter create .`
# only adds missing files, it will not overwrite lib/ or pubspec.yaml.

set -e

echo "==> Checking Flutter installation..."
flutter --version

echo "==> Generating platform folders (android/, ios/, etc.)..."
flutter create . --project-name infra_jejak

echo "==> Fetching packages..."
flutter pub get

echo ""
echo "Done. Next steps:"
echo "  1. (Optional) Set up Firebase — see README.md 'Setup' section."
echo "  2. Open this folder in Android Studio, or run: flutter run"
